#!/usr/bin/env node
const Mustache = require('mustache') 
const fs = require('fs');
const { execSync } = require('child_process');
const canPush = process.argv.indexOf('--push') > -1
var images= JSON.parse(fs.readFileSync('images.json', 'utf8'))
var dockerFiletemplate = fs.readFileSync('Dockerfile', 'utf8')
images.forEach(imageInfo => { 
    var output = Mustache.render(dockerFiletemplate, imageInfo);
    var tag = `${imageInfo.envoy}-${imageInfo.nginx}-${imageInfo.jaeger}-alpine`
    var dockerfileName = `Dockerfile-${tag}`
    fs.writeFileSync(dockerfileName, output)
    var tagName = `envoyproxyplus/envoy-nginx-jaeger:${tag}`
    console.log(`building image for envoy ${imageInfo.envoy} nginx ${imageInfo.nginx}, and jaeger ${imageInfo.jaeger}`)  
    let stdout = execSync(`docker build -t  ${tagName} -f ${dockerfileName} .`)
    console.log(stdout.toString())
    if(canPush)
    {
        stdout = execSync(`docker push ${tagName}`)
        console.log(stdout.toString())    
    }
});